name: Update Registry

on:
  push:
    branches:
      - main

jobs:
  update_registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update registry.json
        run: node updateRegistry.js

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add registry.json
          git diff --staged --exit-code || (git commit -m "Update registry.json" && git push)